/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sysman.demo.common;

import com.sysman.demo.model.APIResponses;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;
import com.sysman.demo.model.Material;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-12T16:21:40.542172662-05:00[America/Bogota]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "material", description = "the material API")
public interface MaterialApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /material : Create a material
     *
     * @param material Optional description in *Markdown* (required)
     * @return Expected response to a valid request (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "createMaterial",
        summary = "Create a material",
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/material",
        produces = { "application/json" },
        consumes = { "application/json", "application/xml" }
    )
    
    default ResponseEntity<APIResponses> createMaterial(
        @Parameter(name = "Material", description = "Optional description in *Markdown*", required = true) @Valid @RequestBody Material material
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /material : List all material
     *
     * @return A paged array of material (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "listMaterial",
        summary = "List all material",
        tags = { "material" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A paged array of material", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/material",
        produces = { "application/json" }
    )
    
    default ResponseEntity<APIResponses> listMaterial(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /material/{city} : Info for a specific material for city
     *
     * @param city The city of the material to retrieve (required)
     * @return Expected response to a valid request (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "showMaterialByCity",
        summary = "Info for a specific material for city",
        tags = { "material" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/material/{city}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<APIResponses> showMaterialByCity(
        @Parameter(name = "city", description = "The city of the material to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("city") String city
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /material/{type} : Info for a specific material for type
     *
     * @param type The id of the product to retrieve (required)
     * @return Expected response to a valid request (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "showMaterialByType",
        summary = "Info for a specific material for type",
        tags = { "material" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/material/{type}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<APIResponses> showMaterialByType(
        @Parameter(name = "type", description = "The id of the product to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("type") String type
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /material/{purchaseAt} : Info for a specific material for purchaseAt
     *
     * @param purchaseAt The purchaseAt of the material to retrieve (required)
     * @return Expected response to a valid request (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "showMaterialBypurchaseAt",
        summary = "Info for a specific material for purchaseAt",
        tags = { "material" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/material/{purchaseAt}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<APIResponses> showMaterialBypurchaseAt(
        @Parameter(name = "purchaseAt", description = "The purchaseAt of the material to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("purchaseAt") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) Date purchaseAt
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /material : Update a material
     *
     * @param material Optional description in *Markdown* (required)
     * @return Expected response to a valid request (status code 200)
     *         or An object with error information (status code 400)
     *         or An object with error information (status code 500)
     */
    @Operation(
        operationId = "updateMaterial",
        summary = "Update a material",
        responses = {
            @ApiResponse(responseCode = "200", description = "Expected response to a valid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "400", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            }),
            @ApiResponse(responseCode = "500", description = "An object with error information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = APIResponses.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/material",
        produces = { "application/json" },
        consumes = { "application/json", "application/xml" }
    )
    
    default ResponseEntity<APIResponses> updateMaterial(
        @Parameter(name = "Material", description = "Optional description in *Markdown*", required = true) @Valid @RequestBody Material material
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"process\" : \"process\", \"code\" : \"code\", \"data\" : [ { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] }, { \"city\" : [ { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] }, { \"code\" : \"code\", \"name\" : \"name\", \"counties\" : [ { \"code\" : \"code\", \"name\" : \"name\" }, { \"code\" : \"code\", \"name\" : \"name\" } ] } ], \"name\" : \"name\", \"description\" : \"description\", \"type\" : \"type\", \"saleAt\" : \"2017-07-21T17:32:28Z\", \"purchaseAt\" : \"2017-07-21T17:32:28Z\", \"status\" : [ \"ACTIVE\", \"ACTIVE\" ] } ], \"executed\" : \"executed\", \"uri\" : \"uri\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
